from src.pre_built.sorting import sort_by

jobs = [
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 20000,
        "max_salary": 35000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-25",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Back-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 10000,
        "max_salary": 50000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-18",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Front-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 30000,
        "max_salary": 40000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Full Stack Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
]


min_salary_criteria = [
    {
        "job_title": "Analista Back-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 10000,
        "max_salary": 50000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-18",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 20000,
        "max_salary": 35000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-25",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Front-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 30000,
        "max_salary": 40000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Full Stack Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
]

max_salary_criteria = [
    {
        "job_title": "Analista Back-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 10000,
        "max_salary": 50000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-18",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Front-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 30000,
        "max_salary": 40000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 20000,
        "max_salary": 35000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-25",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Full Stack Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
]

date_posted_criteria = [
    {
        "job_title": "ABA Therapist",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 20000,
        "max_salary": 35000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-25",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Back-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 10000,
        "max_salary": 50000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-05-18",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Front-End Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": 30000,
        "max_salary": 40000,
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
    {
        "job_title": "Analista Full Stack Da Trybe",
        "company": "Kids Learning Loft Applied Behavior Analysis Services",
        "state": "NY",
        "city": "Williston Park",
        "min_salary": "",
        "max_salary": "",
        "industry": "",
        "rating": "",
        "date_posted": "2020-04-19",
        "valid_until": "2020-06-07",
        "job_type": "PART_TIME",
        "id": "6",
    },
]


def test_sort_by_criteria():
    sort_by(jobs, "min_salary")
    assert jobs == min_salary_criteria

    sort_by(jobs, "max_salary")
    assert jobs == max_salary_criteria

    sort_by(jobs, "date_posted")
    assert jobs == date_posted_criteria
